using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EvolutionaryOptimization
{
    /// <summary>
    /// Class which handles scattered crossover for individuals of type double[]
    /// </summary>
    public class ScatteredCrossover_DoubleVector : ICrossoverOperator<double[]> 
    {
        /// <summary>
        /// Perform a crossover operation on two parent double[]s
        /// </summary>
        /// <param name="parent1">First parent individual</param>
        /// <param name="parent2">Second parent individual</param>
        /// <param name="rnd">Random number generator to be used</param>
        /// <returns>A child individual, generated by scattered crossover of the two parents</returns>
        public double[] Crossover(double[] parent1, double[] parent2, Random rnd)
        {
            int d = parent1.Length;
            double[] child = new double[d];

            for (int i=0; i<d; i++)
            {
                if (rnd.NextDouble() > 0.5)
                {
                    child[i] = parent1[i];
                }
                else
                {
                    child[i] = parent2[i];
                }
            }

            return child;
        }

        public object Clone()
        {
            return this.MemberwiseClone();
        }
    }
}
